### ISSUE TITLE
mySampler and significant figures

### ISSUE THREAD

**Issue by apcarp** [JeffersonLab/myquery#17]
The command line mySampler application appears to write results with a precision of six significant figures while the web version allows the user to specify the number of decimal places in value responses (default of six decimals).

For example, if the PV value is 0.001234567, mySampler CLI always responds 0.00123456, while mysampler web responds with 0.001234 by default.

I'm not sure the best way to address this.  One option is to adjust the meaning of the "f" parameter to be number of significant figures instead of decimal places.  That would be a breaking change, so it's not a great choice.  Something to think about.

```bash
> mySampler -b 2023-09-01 -n 5 -s 1d R1M1GMES
        Date        R1M1GMES
2023-09-01 00:00:00  16.0027
2023-09-02 00:00:00  15.9972
2023-09-03 00:00:00  15.9981
2023-09-04 00:00:00  16.0022
2023-09-05 00:00:00  15.9981
```

https://epicsweb.jlab.org/myquery/mysampler?c=R1M1GMES&b=2023-09-01&n=5&s=86400000&m=&f=&v=
```json
{
  "channels": {
    "R1M1GMES": {
      "metadata": {
        "name": "R1M1GMES",
        "datatype": "DBR_DOUBLE",
        "datasize": 1,
        "datahost": "opsmya8",
        "ioc": "iocnl22rffcc1",
        "active": true
      },
      "data": [
        {
          "d": "2023-09-01T00:00:00",
          "v": 16.002701
        },
        {
          "d": "2023-09-02T00:00:00",
          "v": 15.9972
        },
        {
          "d": "2023-09-03T00:00:00",
          "v": 15.9981
        },
        {
          "d": "2023-09-04T00:00:00",
          "v": 16.002199
        },
        {
          "d": "2023-09-05T00:00:00",
          "v": 15.9981
        }
      ],
      "returnCount": 5
    }
  }
}
```

**Comment by slominskir** [comment]
The `v` parameter is the `Fractional value digits`, while `f` is `Fractional time digits` so actually both are in question here (and I think you mean `v` in your description above).   

Did the upstream API change?   I assume we took the upstream definition `Fractional value digits` years ago.

Aside from the API mismatch between upstream, the actual myquery API seems ok.   I suppose if the app consuming myquery data is using single floats vs doubles then maybe some unnecessary fractional digits could be included in a myquery response assuming fractional digits is set to desired significant figures (and there are digits to the left of the decimal point).   

Changing the meaning of `v` and `f` to mean significant figures would be a major change and require a major version number bump, but is probably fine to do.

**Comment by slominskir** [comment]
Switching the parameters to mean significant figures seems fine with me.  Should be done consistently across the API though, which means updates to Point, Interval, mysampler, and mystats endpoints.

In the event that a user requests few significant figures for a number that has many to the left of the decimal I guess some digits get zero-filled?  Or maybe results should always be in scientific notation in this case (JSON apparently supports scientific notation).  I guess whatever upstream MYA does.

**Comment by apcarp** [comment]
I am not terribly familiar with C++ API , but none of the command line tools I checked provide a channel value precision option.  I included the precision flags to increase internal consistency as they were options in other myquery commands.  The command line help messages don't mention how the precision is handled, but I recently realized from looking at waveform data that this how Chris writes out some data in other C++ applications.

IMO, the major concern is the one Theo lays out.  Consider querying PVs for two different systems.  System A has values in the 1e6 range and system B has values in the 1e-9 range.  The default v=6 option would likely make system B values all 0, and provide unnecessary precision to system A.  Users could try to determine highest required precision for all PVs, but it isn't trivial and involves tradeoffs (over-precision vs under-precision) if dealing in number of decimal places.  This escalates the problem from just a compatibility problem to one about data "truthiness."

I don't think time precision needs to change since time units are consistent and measured at a single scale.  It seems like this is also a concern for the other myquery commands for the same reason as above.

Are we agreed that this should be changed?  If so, what's the priority on addressing this?

**Comment by apcarp** [comment]
Scientific notation can be more verbose, but very clear as to the precision, value and scale.  I think I prefer that as opposed to sending absolute values like 123,456,000.0 and hoping users correctly infer what's going on.

**Comment by apcarp** [comment]
I can get to it eventually, but if you can hit it sooner that's great.  I'm trying to focus on getting another project moving again.  I don't really want to stop now to fix this and test the handful of dependencies.  The fix probably is simple if moving to scientific notation.

**Comment by theojlab** [comment]
Switching to all scientific notation all the time seems ugly.  Are integers all going to be x10^0?  It also makes it difficult to compare datasets generated with the old mySampler against those generated with the new.  The ideal seems to be something like what the %g formatter to printf does "take a number that could be represented as %f (a simple float or double) or %e (scientific notation) and return it as the shorter of the two.".  I have to imagine that's what Chris does in C++ based mya tools.

**Comment by apcarp** [comment]
I think Java supports %g.  I don't care too much one way or the other, as long as clients can figure out the possibly mixed format numbers.

I'm pretty sure C++ code uses the "std::cout.precision(x)" approach that keeps number in decimal format, but gives the requested number of sigfigs.  myget doesn't do the intelligent switching at least.  This feels awkward in the opposite way and would still present challenges for comparing old and new data sets.

https://cplusplus.com/reference/iomanip/setprecision/

```bash
[26] 13:22:25 adamc@devl21 > myget -b 2023-09-15 -e 2023-09-16 -c VIP1L25B
2023-09-15 01:09:03 0.000000000936344
2023-09-15 01:09:11 0.000000000993277
2023-09-15 01:09:52 0.000000000936344
...
```

**Comment by slominskir** [comment]
Previously I was relying Java's DecimalFormat class (which was configured to never use scientific notation), but the latest pull request relies on Java's BigDecimal [toString](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#toString--) method (implicitly), which uses scientific notation only when it "an exponent is needed".   Given that scientific notation is valid JSON this seems reasonable.   Many users will likely be using their favorite programming languages JSON parser package, which will possibly completely hide this detail as they'll be just working with floating point numbers.   If this isn't acceptable let me know as I think we can force the app to never use scientific notation by simply explicitly calling [toPlainString](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#toPlainString--) instead.
